src/blog/urls.py
from django.urls import path
from . import views
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from .feeds import LatestPostsFeed

sitemaps={'posts':PostSitemap}
app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.PostListView.as_view(), name='post-list'),
    path('feed/',LatestPostsFeed(),name='post-feed'),
    path('search/',views.post_search,name='post-search'),
    path('<slug:post>/',
         views.post_detail, name='post-detail'),
    path('<int:post_id>/share/', views.post_share, name='post-share'),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    
]

src/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('tags/', include('tags.urls', namespace='tags')),

    #path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/templates/base/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html>

    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300&family=Montserrat&display=swap" rel="stylesheet">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
        <link href="{% static 'css/styles-sh.css' %}" rel="stylesheet">
    </head>
    <link rel="stylesheet" href="{% static '/css/materialdesignicons.min.css'%}">

    <body>
        <div id="sidebar" class="column">
            <div class="top-left">top left</div>
                <div class="bottom">
                    <div class="avatar">
                        <img src="{%static 'img/sw.jpg'%}">
                    </div>
                    <ul class="nav__main">
                        <li class="bold">
                            <a aria-label="" href="#about" class="">
                                <span class="mdi mdi-share-variant-outline">
                                </span><span>About</span>
                            </a>
                        </li>
                        <li class="bold">
                            <a aria-label="" href="#about" class="">
                                <span class="mdi mdi-trending-up">
                                </span><span>Experience</span></a>
                            </li>
                        <li class="bold">
                            <a aria-label="" href="#about" class="">
                                <span class="mdi mdi-equalizer">
                                </span><span>Skills</span></a>
                        </li>
                        <li class="bold">
                            <a aria-label="" href="#about" class="">
                                <span class="mdi mdi-monitor-cellphone">
                                </span><span>Projects</span>
                            </a>
                        </li>
                        <li class="bold">
                            <a aria-label="" href="#about" class="">
                                <span class="mdi mdi-email-outline">
                                </span><span>Contact</span>
                            </a>
                        </li>
                        
                        <li class="bold">
                            <a aria-label="" href="{%url 'blog:post-list'%}" class="{% if 'blog' in request.path %}active{%endif%}">
                                <span class="mdi mdi-newspaper-variant-outline">
                                </span><span>Blog</span>
                            </a>
                        </li>
                        <li class="bold">
                            <a aria-label="" href="#about" class="">
                                <span class="mdi mdi-school-outline">
                                </span><span>Education</span>
                            </a>
                        </li>
                        <li class="bold">
                            <a aria-label="" href="#about" class="">
                                <span class="mdi mdi-share-variant-outline">
                                </span><span>Resume</span>
                            </a>
                        </li>
                    </ul>
                    <h4><a href="{% url 'blog:post-feed'%}">Subscribe to my RSS feed</a></h4>
                    <h4>Latest Posts</h4>
                    {% show_latest_posts 3 %}
                    <h4>Most commented Posts</h4>
                    {% get_most_commented_posts as most_commented_posts %}
                    <ul>
                        {% for post in most_commented_posts %}
                            <li><a href='{{post.get_absolute_url}}'>{{post.title}}</a></li>
                        {%endfor%}
                    </ul>
              </div>

        </div>
        <div id="content" class="column">
            <div class="top-right">top right</div>
            <div class="bottom">
                <div class="content__main">
                   
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>

</html>

src/templates/base/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>