src/blog/urls.py
from django.urls import path
from . import views
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from .feeds import LatestPostsFeed

sitemaps={'posts':PostSitemap}
app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.PostListView.as_view(), name='post-list'),
    path('feed/',LatestPostsFeed(),name='post-feed'),
    path('search/',views.post_search,name='post-search'),
    path('<slug:post>/',
         views.post_detail, name='post-detail'),
    path('<int:post_id>/share/', views.post_share, name='post-share'),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    
]

src/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('tags/', include('tags.urls', namespace='tags')),

    #path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/templates/post/detail.html
{% extends "base/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">
    Published {{ post.publish }} by {{ post.author }} |
    {% for obj in post.tags.all %}
<div class="col-lg-12">
    <h2>{{ obj.title }}</h2>

</div>
<br>
{% endfor %}
</p>
{{ post.body|markdown}}
<p>
    <a href="url 'blog:post_share' post.id ">
        Share this post
    </a>
</p>

<h2>Similar Posts</h2>
{% for post in similar_posts %}
<p><a href="{{post.get_absolute_url}}">{{post.title}}</a></p>
{%empty%}
<p>No similar posts</p>
{%endfor%}

{% with comments.count as total_comments %}
<h2>
    {{total_comments}} comment{{total_comments|pluralize}}
</h2>
{% endwith %}

{% for comment in comments %}
<div class="comment">
    <p class="info">Comment {{forloop.counter}} by {{comment.name}}
        {{comment.created}}
    </p>
    {{comment.body|linebreaks}}
</div>
{% empty %}
<p>There are no comments yet</p>
{% endfor %}
{% if new_comment %}
<h2>Your comment has been added</h2>
{% else %}
<h2>Add new comment</h2>
<form method="post">
    {{comment_form.as_p}}
    {% csrf_token %}
    <input type="submit" value="Add comment">
</form>
{%endif%}
{% endblock %}

src/templates/post/latest_posts.html
<ul>
    {%for post in latest_posts %}
        <li>
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
        </li>
    {%endfor%}
</ul>

src/templates/post/list.html
{% extends "base/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}

{% block content %}
<h1>My Blog</h1>
There are {% total_posts %} posts
{% for post in posts %}

{% for obj in post.tags.all %}
<div class="col-lg-12">
    <h2>{{ obj.title }}</h2>

</div>
<br>
{% endfor %}


<h2>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</h2>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>


<p>{{ post.body|safe }}</p>
{% endfor %}
{% include "base/pagination.html" with page=page_obj %}
{% endblock %}

src/templates/post/search.html
{% extends "base/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
          Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {{ post.body|markdown|truncatewords_html:5 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "blog:post-search" %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}

src/templates/post/share.html
{% extends "base/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
{% if sent %}
<h1>E-mail successfully sent</h1>
<p>
    "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
</p>
{% else %}
<h1>Share "{{ post.title }}" by e-mail</h1>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock %}